name:                purescript-tsd-gen
version:             0.3.0.0
github:              "minoki/purescript-tsd-gen"
license:             BSD3
author:              "ARATA Mizuki <minorinoki@gmail.com>"
maintainer:          "ARATA Mizuki <minorinoki@gmail.com>"
copyright:           "2018-2019 ARATA Mizuki"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            "TypeScript Declaration File (.d.ts) generator for PureScript"
category:            Language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/minoki/purescript-tsd-gen#readme>

flags:
  purs-v0_14:
    description: "Build against purescript-v0.14.x"
    manual: False
    default: False

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- text
- mtl
- containers
- filepath
- directory

when:
- condition: "flag(purs-v0_14)"
  dependencies:
  - purescript == 0.14.0
  - purescript-ast
- condition: "!flag(purs-v0_14)"
  dependencies:
  - purescript >= 0.13.0 && < 0.14

ghc-options:
- -Wall

library:
  source-dirs: src
  other-modules:
  - Language.PureScript.Constants.Compat
  - Language.PureScript.Environment.Compat
  - Language.PureScript.Externs.Compat
  - Language.PureScript.Kinds.Compat
  - Language.PureScript.Pretty.Compat
  - Language.PureScript.TsdGen.Hardwired
  - Language.PureScript.TsdGen.Module.ReadExterns
  - Paths_purescript_tsd_gen

executables:
  purs-tsd-gen:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - purescript-tsd-gen
    - optparse-applicative

tests:
  doctests:
    main:                doctests.hs
    dependencies:
    - doctest >= 0.8
    - QuickCheck
