name:                purescript-tsd-gen
version:             0.3.0.0
github:              "minoki/purescript-tsd-gen"
license:             BSD3
author:              "ARATA Mizuki <minorinoki@gmail.com>"
maintainer:          "ARATA Mizuki <minorinoki@gmail.com>"
copyright:           "2018-2021 ARATA Mizuki"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            "TypeScript Declaration File (.d.ts) generator for PureScript"
category:            Language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/minoki/purescript-tsd-gen#readme>

flags:
  purescript-15:
    description: "Build against purescript only package (purescript-0.15)"
    manual: False
    default: False
  purescript-ast:
    description: "Build against purescript-ast package (purescript-0.14.{0,1})"
    manual: False
    default: False
  purescript-cst:
    description: "Build against purescript-cst package (purescript-0.14.2)"
    manual: False
    default: False

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- text
- mtl
- containers
- filepath
- directory

when:
- condition: "flag(purescript-15)"
  dependencies:
  - purescript >= 0.15.4
- condition: "flag(purescript-cst) && !flag(purescript-ast) && !flag(purescript-15)"
  dependencies:
  - purescript >= 0.14.2 && < 0.15
  - purescript-cst
- condition: "flag(purescript-ast) && !flag(purescript-cst) && !flag(purescript-15)"
  dependencies:
  - purescript >= 0.14.0 && < 0.14.2
  - purescript-ast
- condition: "!flag(purescript-ast) && !flag(purescript-cst) && !flag(purescript-15)"
  dependencies:
  - purescript >= 0.13.0 && < 0.14

ghc-options:
- -Wall
- -Wcompat

executables:
  purs-tsd-gen:
    main:                Main.hs
    source-dirs:
    - app
    - src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - optparse-applicative

tests:
  doctests:
    main:                doctests.hs
    dependencies:
    - doctest >= 0.8
    - QuickCheck
