name:                purescript-tsd-gen
version:             0.2.0.0
github:              "minoki/purescript-tsd-gen"
license:             BSD3
author:              "ARATA Mizuki <minorinoki@gmail.com>"
maintainer:          "ARATA Mizuki <minorinoki@gmail.com>"
copyright:           "2018 ARATA Mizuki"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            "TypeScript Declaration File (.d.ts) generator for PureScript"
category:            Language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/minoki/purescript-tsd-gen#readme>

dependencies:
- base >= 4.7 && < 5
- purescript >= 0.12.0
- aeson
- bytestring
- text
- mtl
- containers
- filepath
- directory

library:
  source-dirs: src

executables:
  purs-tsd-gen:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - purescript-tsd-gen
    - optparse-applicative
