resolver: lts-20.9

packages:
  - .

extra-deps:
  - purescript-0.15.15
  - language-javascript-0.7.0.0
  - hspec-2.10.9
  - hspec-core-2.10.9
  - hspec-discover-2.10.9
  - process-1.6.13.1
  - Cabal-3.6.3.0

flags:
  aeson-pretty:
    lib-only: true
  these:
    assoc: false
  haskeline:
    terminfo: false
